# Site settings
title: Tristan Blog
SEOTitle: 美川的博客 | Tristan Blog
header-img: img/home-bg.jpg
email: TristanHuang0501@gmail.com
description: "子路问津 | 黄美川, tirstanhuang | 这里是 @TristanHuang0501 黄美川 的个人博客，与你一起发现更大的世界。"
keyword: "黄美川, tristanhuang, 黄美川的博客, tristan Blog, 博客, 个人网站, 互联网"
url: "http://TristanHuang0501.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     mei-chuan-huang
github_username:    TristanHuang0501
twitter_username:   false
facebook_username:  tristanhuang0501
csdn_username:  h_meichuan
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems:
  - jekyll-paginate
  - jemoji



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: tristanhuang
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                      # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-93366010-1'            # Format: UA-xxxxxx-xx
ga_domain: tristanhuang0501.github.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "温良恭俭，当仁不让"
sidebar-avatar: /img/tristan.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Jerry Yip",
        href: "http://jerryyip.github.io"
    },{
        title: "eastfisher",
        href: "http://eastfisher.org/"
    },{
        title: "板哥",
        href: "http://ursolovely.top"
    }

]
